parameters:
#    smart_news_home.example.class: SmartNews\HomeBundle\Example

services:
#    smart_news_home.example:
#        class: %smart_news_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
