parameters:
#    smart_news_user.example.class: SmartNews\UserBundle\Example

services:
#    smart_news_user.example:
#        class: %smart_news_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
